### ISSUE TITLE
1.0 Version Roadmap

### ISSUE THREAD

**Issue by hkzorman** [hkzorman/advanced_npc#10]
This issue is to keep track of what is still lacking in the mod in order to have a 1.0 release.

- [ ] Content:
  - [ ] Textures: add at least 3-5 more textures for males and females, including children.
  - [ ] Dialogues: add at least a 100 dialogue lines that are generic enough
  - [ ] Prices: add prices for all default items
  - [ ] Names: add at least 50 more names for both males and females
  - [ ] Relationships: add at least 10 more unique liked items and disliked item for each phase
- [ ] Actions:
  - [ ] Add actions to place and dig nodes
- [ ] Schedules:
  - [ ] Add ability to override some of the NPC's attributes (like trader status)
- [ ] Jobs: #7 
- [ ] Spawner: #6 
- [ ] Places: finish implementation of places, #1

**Comment by hkzorman** [comment]
While the actions/schedules functionality is mostly complete at this time, a technical change in the API and the introduction of new actions/commands will enable the API to be as flexible as possible and to build new behaviors in NPCs.

#### Proposed changes:
  - Unify the actions/tasks/schedule property change/schedule query API into a `commands` API
  - Add new commands to bring the NPC interaction level closer to that of a player
  - Rename `flags` to `properties`
  - Allow registering scripts, or collections of commands for external mods to provide extra functionality
